---
title: "Phillips Graph"
output:
  html_document: default
  pdf_document: default
date: "2022-10-18"
---

```{r setup, include=FALSE}
library(tidyverse)
```

```{r load data}
fredRaw = read.csv("fredgraph.csv")
```

```{r cleaning and manipulating data}
fred <- fredRaw %>%
  mutate(year = as.numeric(strtrim(DATE, 4)),
         month = as.numeric(substring(DATE, 6, 7))) %>%
  filter(year >= 1959) %>%
  filter(month == 10) %>%
  transform(prev_cpi = c(NA, CPIAUCSL[-length(CPIAUCSL)])) %>%
  mutate(
    cpi_change = (CPIAUCSL - prev_cpi) / prev_cpi,
    dec = substr(DATE, 1, 3),
    ade = "0s",
    decade = paste(dec, ade, sep = "")
  ) %>%
  filter(year >= 1960) %>%
  mutate(unemployment = as.double(UNRATE))

fred %>%
  summarise(year, unemployment, cpi_change)
```

```{r graph}
fred %>%
  ggplot(aes(x = unemployment, y = cpi_change, color = decade)) +
  geom_point() +
  labs(
    title = "Phillip's Curve",
    x = "Unemployment Rate",
    y = "Inflation Rate",
    color = "Decade"
)
```



